package com.akademi.enums;

public enum NotificationCategory {
    BOOKING_CONFIRMED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,
    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    INCIDENT_RESOLVED,
    SLA_WARNING,
    SLA_BREACH,
    GENERAL
}
